### PR TITLE
fix bump coffee script compiler on parameter variable

### PR DESCRIPTION
**Pull request by kakada**

### CODE REVIEW

**Comment by bcardiff** [comment]
¿Are you using the ruby-hub_client directly?

**Comment by kakada** [comment]
Yes, I do

**Comment by bcardiff** [comment]
Check mbuilder or verboice to see how to use it. Or feel free to ask. It's very young ;-)

**Comment by kakada** [comment]
Will let you know if we have any problems/questions, thanks ;-)

**Pull request merged**
